"""
Script 4: Prompt Templates for CVSS Component Prediction
=========================================================
Generates zero-shot and few-shot prompts for all 4 models.
Few-shot examples use Option B: concise structured reasoning + JSON.

The few-shot examples are loaded from few_shot.csv (generated by Script 1).
Each example includes:
  - CVE description
  - Short metric-by-metric justification (1 line per component)
  - Final JSON output

Same prompts used for ALL models — ensures fair comparison.

Usage:
    from prompts import build_zero_shot, build_few_shot, load_few_shot_examples
"""

import pandas as pd
from pathlib import Path

# ── Component Descriptions ────────────────────────────────────
COMPONENT_GUIDE = """
CVSS v3.1 Base Metric Reference:
- AV (Attack Vector):        N=Network, A=Adjacent, L=Local, P=Physical
- AC (Attack Complexity):    L=Low, H=High
- PR (Privileges Required):  N=None, L=Low, H=High
- UI (User Interaction):     N=None, R=Required
- S  (Scope):                U=Unchanged, C=Changed
- C  (Confidentiality):      N=None, L=Low, H=High
- I  (Integrity):            N=None, L=Low, H=High
- A  (Availability):         N=None, L=Low, H=High
""".strip()

# ── Zero-Shot Prompt ──────────────────────────────────────────
ZERO_SHOT_TEMPLATE = """\
You are a cybersecurity expert specializing in CVSS v3.1 vulnerability scoring.

Your task is to analyze the vulnerability description below and predict the 8 CVSS v3.1 base metric values.

{component_guide}

Scoring hints:
- If exploitable over a network without physical access → AV: N
- If no special privileges needed → PR: N
- If no user action required → UI: N
- If impact is contained to the vulnerable system → S: U
- Rate C/I/A based on what the attacker can access or disrupt

Return ONLY a valid JSON object with exactly these 8 keys. No explanation, no markdown, no extra text:
{{"AV": "?", "AC": "?", "PR": "?", "UI": "?", "S": "?", "C": "?", "I": "?", "A": "?"}}

Description:
{description}"""


# ── Few-Shot Prompt Builder ───────────────────────────────────

def format_few_shot_example(row: pd.Series) -> str:
    """
    Format one CVE as a few-shot example.
    Format: Description → Reasoning (one line per component) → Output JSON
    CVE ID is deliberately excluded to prevent memorization bias.
    """
    comp = {k: row[k] for k in ["AV", "AC", "PR", "UI", "S", "C", "I", "A"]}

    # Concise one-line reasoning per component
    reasoning_map = {
        "AV": {
            "N": "AV:N — exploitable remotely over the network.",
            "A": "AV:A — requires adjacent network access.",
            "L": "AV:L — requires local system access.",
            "P": "AV:P — requires physical access to the device.",
        },
        "AC": {
            "L": "AC:L — no special conditions or complexity required.",
            "H": "AC:H — exploitation requires specific conditions or timing.",
        },
        "PR": {
            "N": "PR:N — no authentication or privileges required.",
            "L": "PR:L — requires basic user-level privileges.",
            "H": "PR:H — requires administrative or high-level privileges.",
        },
        "UI": {
            "N": "UI:N — no user interaction required.",
            "R": "UI:R — a user must take an action to trigger exploitation.",
        },
        "S": {
            "U": "S:U — impact is confined to the vulnerable component.",
            "C": "S:C — impact can extend beyond the vulnerable component.",
        },
        "C": {
            "N": "C:N — no confidentiality impact.",
            "L": "C:L — partial information disclosure.",
            "H": "C:H — complete or critical confidentiality loss.",
        },
        "I": {
            "N": "I:N — no integrity impact.",
            "L": "I:L — partial data modification possible.",
            "H": "I:H — complete or critical integrity loss.",
        },
        "A": {
            "N": "A:N — no availability impact.",
            "L": "A:L — partial availability disruption.",
            "H": "A:H — complete or critical availability loss.",
        },
    }

    reasoning_lines = "\n".join(
        reasoning_map[k][comp[k]]
        for k in ["AV", "AC", "PR", "UI", "S", "C", "I", "A"]
    )

    json_output = (
        f'{{"AV": "{comp["AV"]}", "AC": "{comp["AC"]}", '
        f'"PR": "{comp["PR"]}", "UI": "{comp["UI"]}", '
        f'"S": "{comp["S"]}", "C": "{comp["C"]}", '
        f'"I": "{comp["I"]}", "A": "{comp["A"]}"}}'
    )

    return (
        f"Description:\n{row['Description'].strip()}\n\n"
        f"Reasoning:\n{reasoning_lines}\n\n"
        f"Output:\n{json_output}"
    )


def load_few_shot_examples(few_shot_path: str = "few_shot.csv") -> list[str]:
    """Load and format few-shot examples from CSV."""
    path = Path(few_shot_path)
    if not path.exists():
        raise FileNotFoundError(f"{few_shot_path} not found. Run 1_build_dataset.py first.")

    df = pd.read_csv(path)
    examples = []
    for _, row in df.iterrows():
        examples.append(format_few_shot_example(row))

    return examples


FEW_SHOT_TEMPLATE = """\
You are a cybersecurity expert specializing in CVSS v3.1 vulnerability scoring.

Your task is to analyze the vulnerability description below and predict the 8 CVSS v3.1 base metric values.

{component_guide}

Here are examples showing the expected reasoning and output format:

{examples}

---
Now analyze the following vulnerability using the same reasoning pattern.

Return ONLY a valid JSON object with exactly these 8 keys. No explanation, no markdown, no extra text:
{{"AV": "?", "AC": "?", "PR": "?", "UI": "?", "S": "?", "C": "?", "I": "?", "A": "?"}}

Description:
{description}"""


# ── Public Functions ──────────────────────────────────────────

def build_zero_shot(description: str) -> str:
    """Build zero-shot prompt for a CVE description."""
    return ZERO_SHOT_TEMPLATE.format(
        component_guide=COMPONENT_GUIDE,
        description=description.strip(),
    )


def build_few_shot(description: str,
                   few_shot_examples: list[str] | None = None,
                   few_shot_path: str = "few_shot.csv") -> str:
    """Build few-shot prompt for a CVE description."""
    if few_shot_examples is None:
        few_shot_examples = load_few_shot_examples(few_shot_path)

    numbered = "\n\n---\n".join(
        f"Example {i+1}:\n{ex}"
        for i, ex in enumerate(few_shot_examples)
    )

    return FEW_SHOT_TEMPLATE.format(
        component_guide=COMPONENT_GUIDE,
        examples=numbered,
        description=description.strip(),
    )


def get_prompt(prompt_type: str,
               description: str,
               few_shot_examples: list[str] | None = None) -> str:
    """Dispatcher — returns correct prompt based on type."""
    if prompt_type == "zero_shot":
        return build_zero_shot(description)
    elif prompt_type == "few_shot":
        return build_few_shot(description, few_shot_examples)
    else:
        raise ValueError(f"Unknown prompt type: {prompt_type}")


def estimate_token_count(text: str) -> int:
    """Rough token estimate (1 token ≈ 4 chars)."""
    return len(text) // 4


if __name__ == "__main__":
    # Test with a sample description
    sample = ("A SQL injection vulnerability in the login endpoint allows "
               "unauthenticated remote attackers to execute arbitrary SQL commands "
               "and read sensitive database contents without any user interaction.")

    zs = build_zero_shot(sample)
    print("ZERO-SHOT PROMPT")
    print("=" * 50)
    print(zs)
    print(f"\nEstimated tokens: {estimate_token_count(zs)}")

    print("\n\nFEW-SHOT PROMPT (requires few_shot.csv)")
    print("=" * 50)
    try:
        fs = build_few_shot(sample)
        print(fs[:500] + "...")
        print(f"\nEstimated tokens: {estimate_token_count(fs)}")
    except FileNotFoundError as e:
        print(f"  {e}")
        print("  Run 1_build_dataset.py first to generate few_shot.csv")
